# Uncomment the next line to define a global platform for your project

platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

def common_pods
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
#  pod 'FacebookCore'
#  pod 'FacebookLogin'
  pod 'GoogleSignIn'
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/Buttons'
end

target 'Future-Hope' do
    common_pods
end

target 'Future-Hope-UnitTests' do
  common_pods
end
